#!/bin/sh
mkdir -p dist

# Minified and stripped CullJS production build
cd lib/culljs
npm install
node build -m -s -n
cd ../..

# Minified and stripped Dome production build
cd lib/dome
npm install
node build -m -s -n
cd ../..

# Combine it all
cat \
    lib/culljs/dist/cull.min.js \
    lib/dome/dist/dome.min.js \
    lib/spin.js/dist/spin.min.js > dist/gts-ui-deps.js
