#!/usr/bin/sh
mkdir -p dist

# Minified and stripped CullJS production build
cd js/lib/culljs
npm install
node build -s -n
cd ../../..

# Minified and stripped Dome production build
cd js/lib/dome
npm install
node build -s -n
cd ../../..

# Combine 'em all
cat \
    js/lib/culljs/dist/cull.js \
    js/lib/dome/dist/dome.js \
    js/lib/spin.js/spin.js \
    js/lib/when/when.js \
    js/lib/bane/lib/bane.js \
    js/lib/reqwest/reqwest.js \
    js/lib/uinit/lib/uinit.js \
    js/lib/showdown/src/showdown.js \
    js/src/app.js \
    js/src/components/dropdown.js \
    js/src/components/ganalytics.js \
    js/src/components/abbrev.js \
    js/src/components/url.js \
    js/src/components/ref-selector.js \
    js/src/components/tree-history.js \
    js/src/components/commit-linker.js \
    js/src/components/user-repo-view-state.js \
    js/src/components/profile-menu.js \
    js/src/components/clone-url-selection.js \
    js/src/components/blob.js \
    js/src/components/live-markdown-preview.js \
    js/src/gitorious.js | ./node_modules/.bin/uglifyjs > dist/gitorious3.min.js

du -sh dist/gitorious3.min.js
